### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by phaedrus2014** [agiovann/Constrained_NMF#22]
Hello

After installing by 'EASY WAY'. I tried to run the demo.py, but this always fails with the following message
No module named SPGL1_python_port.spgl1

Also, during installation, 'conda install atlas' command was not effective.
(Error: No packages found in current osx-64 channels matching: atlas)     

I am currently using OS X El Capitan. 
So I pip-installed atlas.(system message below)

Collecting atlas
Collecting threadpool>=1.2.4 (from atlas)
  Using cached threadpool-1.3.2-py2-none-any.whl
Installing collected packages: threadpool, atlas
Successfully installed atlas-0.27.0 threadpool-1.3.2

Is my problem related to 'atlas' installation?  Or, other problem is occurring?
What should I do next ?
Thanks

**Comment by agiovann** [comment]
Dear phaedrus2014,

thank you for the feedback! We tried on el capitan and it worked after some minor changes. Please try to create a new environment and reinstall everything. 

Please let us know if it works otherwise we will try something different

**Comment by phaedrus2014** [comment]
Dear agiovann,

Really appreciate for quick and kind reply. 
I reinstalled anaconda(ver.2.4.1) on El Capitan and demo works now. Beautiful!

I'd like to ask some very basic questions.
How should I actually use this program to analyze my data?
Is it possible just by putting my data in movies folder, and change some parameters in the code like below?

movie_name='movies/**my_data.tif**'
movie_mc_name='movies/**my_data.hdf5**'
frate=**my_data_frame_rate**
max_shift_w,max_shift_h=**estimated_shift_x,estimated_shift_y**
(+Setting parameters for the server and the order of the AR mode)


In my own experiment, neurons are expressing GCaMP and RFP. So,I obtain two-channel image data.
Is it possible to analyze two-channel image with this program?
Also, is it possible to use a second static channel(RFP) to estimate the displacements and apply this information to both channels for motion correction?


I am sorry to make so many requests despite your busyness.
Sincerely,

**Comment by agiovann** [comment]
Dear Pheadrus,

what you mention should work (reorganizing the folders). I assume you are using demo_pipeline.py, that is something only  at an experimental stage. I will try to write something more systematic about it, and possibly introduce an example with multiple channels in the next days. At the moment multiple channels are not supported but it should not be too difficult to incorporate them into motion correction. However CNMF will only use one channel.

Best,

Andrea
