### ISSUE TITLE
in the notebook the patches are not drawn correctly, especially in the corners

### ISSUE THREAD

**Issue by agiovann** [agiovann/Constrained_NMF#5]

**Comment by agiovann** [comment]
the error is due to the was coordinates are returned by plot_contours (especially around the borders). Eftychios, see if you can adapt the output so that the borders are someway included.

**Comment by epnev** [comment]
it's just a plotting issue.
In plot_contours change
```
plt.imshow(Cn,interpolation=None,cmap=cmap)
```
to
```
plt.imshow(Cn,interpolation=None,cmap=cmap, extent = (0,d2-1,0,d1-1))
```
In the demo file change
```
plt.axis((-0.5,d2-0.5,-0.5,d1-0.5))
```
to
```
plt.axis((0,d2-1,0,d1-1))
```


As far as I can tell the coordinates are stored correctly.
